name: Me Botto

on:
  # schedule:
  #   # every 10 minutes the job will run
  #   - cron: "*/10 * * * *"
  push:
    branches:
      - master
  repository_dispatch:
    types: [my-event]
jobs:
  run-bot:
    runs-on: ubuntu-18.04
    # timeout-minutes: 9  

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    
    - name : Fetch latest HEAD of submodule
      run: |
        pushd webScraper
        git rev-parse --short HEAD
        git submodule update --init --recursive --remote
        git rev-parse --short HEAD
        git checkout master
        git rev-parse HEAD
        popd
    # Remove apt repos that are known to break from time to time
    # See https://github.com/actions/virtual-environments/issues/323
    # - name: Remove broken apt repos [Ubuntu]
    #  run: |
    #      for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
    
    - name: Install OS dependencies
      run: |
          sudo apt-get update
          sudo apt-get install build-essential libpoppler-cpp-dev ghostscript pkg-config locales
    
    - name: Install Python dependencies
      run: pip install --upgrade pip && pip install wheel && pip install -r requirements.txt -r webScraper/requirements.txt
    
    - name: Start Bot
      run: |
        python start.py
      env:
          LANG: "en_US.UTF-8"
          COVID_BOT_TOKEN: ${{ secrets.COVID_BOT_TOKEN }}
          VISIONAPI_TOKEN: ${{ secrets.VISIONAPI_TOKEN }}
          UPDATE_ID: ${{ github.event.client_payload.update_id }}
    
    - name: Repository Dispatch
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.JUN_TOKEN}}
        script: |
          const fs = require('fs');
          update_id = fs.readFileSync('/tmp/update_id', 'utf8');
          console.log("This is the last update_id: "+update_id);
          await github.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: "my-event",
                  client_payload: { greeting: "hello", update_id: update_id }
                });
